apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: icorenux-backstage
  title: Sample Service v2 # optional, human readable component name
  description: My first Backstage catalog item.
  annotations:
    github.com/project-slug: icorenux/backstage
    #backstage.io/techdocs-ref: value
    jenkins.io/job-full-name: "hello"
spec:
  type: service
  owner: user:icorenux
  lifecycle: experimental
